version: "3"

services:
  backend:
    build: ./
    container_name: bizon_container
    working_dir: /bizon
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - static_content:/bizon/src/static
      - media_content:/bizon/src/media
      - ./src:/bizon/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:3-stretch
    container_name: mongodb_cont
    ports:
      - 27017:27017
    command: [ "--bind_ip_all", "--smallfiles" ]
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo_admin_cont
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/bizon/src/static
      - media_content:/bizon/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pg_data: { }
  pgadmin_data: { }
  mongodb_data: { }
  static_content: { }
  media_content: { }