version: "3"

services:
  backend:
    build: ./
    container_name: bizon_container
    working_dir: /bizon
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8008
    volumes:
      - ./src:/bizon/src
    env_file:
      - .env

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  pg_data: { }