# Generated by Django 4.1.1 on 2022-11-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.PositiveIntegerField(),
        ),
    ]
